name: Download latest COVID-19 Status vaccination

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * *

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run download-today-status
      - run: |
          git config user.name ielijose
          git config user.email ielijose@gmail.com
          git add .
          git commit -m "Add report for today"
          git push
